# Generated by Django 3.2.8 on 2021-12-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('stocks', models.IntegerField()),
                ('filename', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
