# Generated by Django 3.2.8 on 2021-12-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MKclothingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='filename',
        ),
    ]
