# Generated by Django 3.2.8 on 2022-01-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKclothingapp', '0003_products_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pname', models.CharField(max_length=20)),
                ('quan', models.IntegerField()),
                ('total', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
