# Generated by Django 3.2.8 on 2022-01-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKclothingapp', '0004_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
