# Generated by Django 3.2.8 on 2022-01-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKclothingapp', '0006_orderc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderc',
            name='can',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderc',
            name='comp',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderc',
            name='tot',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
