# Generated by Django 3.2.8 on 2022-01-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKclothingapp', '0006_orderc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderc',
            name='cancels',
        ),
        migrations.RemoveField(
            model_name='orderc',
            name='success',
        ),
        migrations.AddField(
            model_name='orderc',
            name='can',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderc',
            name='comp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderc',
            name='tot',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
