# Generated by Django 3.2.8 on 2022-01-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKclothingapp', '0007_auto_20220129_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderc',
            name='can',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderc',
            name='comp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderc',
            name='tot',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
