# Generated by Django 3.2.8 on 2022-01-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKclothingapp', '0007_auto_20220131_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderc',
            name='can',
        ),
        migrations.RemoveField(
            model_name='orderc',
            name='comp',
        ),
        migrations.RemoveField(
            model_name='orderc',
            name='tot',
        ),
        migrations.AddField(
            model_name='orderc',
            name='cancel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderc',
            name='success',
            field=models.IntegerField(default=0),
        ),
    ]
