# Generated by Django 3.2.8 on 2022-01-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKclothingapp', '0008_auto_20220129_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderc',
            name='can',
        ),
        migrations.RemoveField(
            model_name='orderc',
            name='comp',
        ),
        migrations.RemoveField(
            model_name='orderc',
            name='tot',
        ),
        migrations.AddField(
            model_name='orderc',
            name='cancels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderc',
            name='success',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderc',
            name='totalorders',
            field=models.IntegerField(default=0),
        ),
    ]
