# Generated by Django 3.2.8 on 2022-01-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKclothingapp', '0010_alter_orderc_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderc',
            name='cancels',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderc',
            name='totalorders',
            field=models.IntegerField(),
        ),
    ]
