# Generated by Django 3.2.8 on 2022-01-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKclothingapp', '0012_alter_orderc_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderc',
            name='success',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
