# Generated by Django 3.2.8 on 2022-01-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKclothingapp', '0016_auto_20220130_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderc',
            name='cancels',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='orderc',
            name='success',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='orderc',
            name='totalorders',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
