# Generated by Django 3.2.8 on 2022-01-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKclothingapp', '0017_auto_20220130_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderc',
            name='totalorders',
        ),
        migrations.AlterField(
            model_name='orderc',
            name='cancels',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderc',
            name='success',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
