# Generated by Django 3.2.8 on 2022-01-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKclothingapp', '0020_auto_20220131_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderc',
            name='place',
            field=models.CharField(default='1', max_length=25, verbose_name='Place'),
        ),
    ]
