# Generated by Django 3.2.8 on 2022-01-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKclothingapp', '0021_orderc_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderc',
            name='place',
        ),
        migrations.AlterField(
            model_name='orderc',
            name='cancels',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderc',
            name='success',
            field=models.IntegerField(default=0),
        ),
    ]
