# Generated by Django 3.2.8 on 2022-01-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKclothingapp', '0023_auto_20220131_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderc',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderc',
            name='success',
            field=models.IntegerField(default=0),
        ),
    ]
