# Generated by Django 3.2.8 on 2022-01-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKclothingapp', '0024_auto_20220131_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderc',
            name='success',
            field=models.IntegerField(),
        ),
    ]
