# Generated by Django 3.2.8 on 2022-01-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKclothingapp', '0025_alter_orderc_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderc',
            name='success',
            field=models.IntegerField(default=0),
        ),
    ]
