# Generated by Django 3.2.8 on 2022-01-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKclothingapp', '0026_alter_orderc_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderc',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderc',
            name='cancels',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderc',
            name='success',
            field=models.IntegerField(),
        ),
    ]
